"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import cloudinary
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega as variáveis do .env.production (procura no diretório backend)
# Tenta diferentes nomes de arquivo em ordem de preferência
env_files = [
    BASE_DIR / '.env.production',
    BASE_DIR / 'env.production',  # Sem ponto no início
    BASE_DIR / '.env',
]

for env_file in env_files:
    if env_file.exists():
        load_dotenv(env_file)
        break


def env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() in ('true', '1', 'yes', 'on')


def env_list(name, default=''):
    value = os.getenv(name, default)
    items = []
    for item in value.split(','):
        cleaned = item.strip().strip('"').strip("'")
        if '=' in cleaned and cleaned.startswith(f'{name}='):
            cleaned = cleaned.split('=', 1)[1].strip().strip('"').strip("'")
        if cleaned:
            items.append(cleaned)
    return items


def db_ca_cert_path():
    ca_cert = os.getenv('DB_CA_CERT') or os.getenv('DB_CA_CERT_CONTENT')
    if not ca_cert:
        return None

    ca_cert = ca_cert.strip().strip('"').strip("'")
    ca_cert = ca_cert.replace('\\n', '\n')

    if 'BEGIN CERTIFICATE' not in ca_cert:
        return ca_cert

    cert_path = Path(os.getenv('DB_CA_CERT_PATH', '/tmp/aiven-ca.pem'))
    if os.name == 'nt' and not os.getenv('DB_CA_CERT_PATH'):
        cert_path = BASE_DIR / '.aiven-ca.pem'

    cert_path.parent.mkdir(parents=True, exist_ok=True)
    cert_path.write_text(ca_cert + '\n', encoding='utf-8')
    return str(cert_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-set-secret-key-in-env'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is false.')

default_allowed_hosts = 'localhost,127.0.0.1' if DEBUG else ''
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', default_allowed_hosts)

render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_hostname:
    ALLOWED_HOSTS.append(render_hostname)

vercel_url = os.getenv('VERCEL_URL')
if vercel_url:
    ALLOWED_HOSTS.append(vercel_url)

if env_bool('VERCEL', False):
    ALLOWED_HOSTS.extend(['.vercel.app', 'projeto-miranda.vercel.app'])

ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS must be set when DEBUG is false.')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', not DEBUG)
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', '1209600' if DEBUG else '28800'))
SESSION_EXPIRE_AT_BROWSER_CLOSE = env_bool('SESSION_EXPIRE_AT_BROWSER_CLOSE', not DEBUG)
MANAGER_TOKEN_TTL_SECONDS = int(os.getenv('MANAGER_TOKEN_TTL_SECONDS', '28800'))
MANAGER_TOKEN_ROTATE_ON_LOGIN = env_bool('MANAGER_TOKEN_ROTATE_ON_LOGIN', True)
DB_SSL_REQUIRED = env_bool('DB_SSL_REQUIRED', True)
BACKUP_PROVIDER = os.getenv('BACKUP_PROVIDER', 'aiven')
BACKUP_FREQUENCY_HOURS = int(os.getenv('BACKUP_FREQUENCY_HOURS', '24'))
BACKUP_MIN_RETENTION_DAYS = int(os.getenv('BACKUP_MIN_RETENTION_DAYS', '7' if DEBUG else '30'))
BACKUP_RETENTION_DAYS = int(os.getenv('BACKUP_RETENTION_DAYS', str(BACKUP_MIN_RETENTION_DAYS)))
BACKUP_RESTORE_TEST_INTERVAL_DAYS = int(os.getenv('BACKUP_RESTORE_TEST_INTERVAL_DAYS', '30'))
BACKUP_LAST_RESTORE_TEST_AT = os.getenv('BACKUP_LAST_RESTORE_TEST_AT', '')
BACKUP_EVIDENCE_URL = os.getenv('BACKUP_EVIDENCE_URL', '')

if not DEBUG:
    required_secure_settings = {
        'SECURE_SSL_REDIRECT': SECURE_SSL_REDIRECT,
        'SESSION_COOKIE_SECURE': SESSION_COOKIE_SECURE,
        'CSRF_COOKIE_SECURE': CSRF_COOKIE_SECURE,
        'SECURE_HSTS_SECONDS': SECURE_HSTS_SECONDS > 0,
    }
    disabled_settings = [
        name for name, enabled in required_secure_settings.items() if not enabled
    ]
    if disabled_settings:
        raise ImproperlyConfigured(
            'Production security settings must be enabled: '
            + ', '.join(disabled_settings)
        )
    if MANAGER_TOKEN_TTL_SECONDS <= 0:
        raise ImproperlyConfigured(
            'MANAGER_TOKEN_TTL_SECONDS must be greater than zero when DEBUG is false.'
        )


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
    'cloudinary',
    'api.apps.ApiConfig',
]

JAZZMIN_SETTINGS = {
    'site_title': 'Administração | Projeto Miranda',
    'site_header': 'NEXA | Projeto Miranda',
    'site_brand': 'Nexa',
    'site_logo': 'admin/img/nexa-logo.png',
    'site_icon': 'admin/img/nexa-icon.svg',
    'site_logo_classes': 'miranda-site-logo',
    'login_logo': 'admin/img/nexa-logo.png',
    'login_logo_dark': 'admin/img/nexa-logo.png',
    'welcome_sign': 'Bem-vindo ao painel administrativo',
    'copyright': 'Projeto Miranda',
    'search_model': ['auth.User', 'api.Announcement', 'api.PushDevice'],
    'topmenu_links': [
        {'name': 'Início', 'url': 'admin:index'},
        {'model': 'auth.User'},
        {'model': 'api.Announcement'},
    ],
    'usermenu_links': [
        {'model': 'auth.User'},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': [],
    'hide_models': [],
    'order_with_respect_to': [
        'api',
        'api.Announcement',
        'api.Segment',
        'api.DeliveryLog',
        'api.PushDevice',
        'api.Institution',
        'api.VisualIdentity',
        'api.Attachment',
        'api.Document',
        'api.Profile',
        'api.PrivacyRequest',
        'api.AuditLog',
        'auth',
        'auth.User',
        'auth.Group',
    ],
    'custom_links': {
        'api': [
            {
                'name': 'Usuários ativos',
                'url': 'admin-report-users-active',
                'icon': 'fas fa-user-check',
                'permissions': ['auth.view_user'],
            },
            {
                'name': 'Comunicados publicados',
                'url': 'admin-report-announcements-published',
                'icon': 'fas fa-bullhorn',
                'permissions': ['api.view_announcement'],
            },
            {
                'name': 'Dispositivos ativos',
                'url': 'admin-report-devices-active',
                'icon': 'fas fa-mobile-alt',
                'permissions': ['api.view_pushdevice'],
            },
            {
                'name': 'Falhas de envio',
                'url': 'admin-report-delivery-failures',
                'icon': 'fas fa-exclamation-triangle',
                'permissions': ['api.view_deliverylog'],
            },
        ],
    },
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.User': 'fas fa-user-shield',
        'auth.Group': 'fas fa-users',
        'api': 'fas fa-layer-group',
        'api.Announcement': 'fas fa-bullhorn',
        'api.Attachment': 'fas fa-paperclip',
        'api.AuditLog': 'fas fa-clipboard-list',
        'api.DeliveryLog': 'fas fa-paper-plane',
        'api.Document': 'fas fa-file-alt',
        'api.Institution': 'fas fa-landmark',
        'api.PrivacyRequest': 'fas fa-user-lock',
        'api.Profile': 'fas fa-id-card',
        'api.PushDevice': 'fas fa-mobile-alt',
        'api.Segment': 'fas fa-object-group',
        'api.VisualIdentity': 'fas fa-palette',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': False,
    'custom_css': 'admin/css/miranda_admin.css',
    'custom_js': None,
    'use_google_fonts_cdn': False,
    'show_ui_builder': False,
    'changeform_format': 'horizontal_tabs',
    'language_chooser': False,
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    'default_theme_mode': 'light',
    'navbar': 'navbar-white navbar-light',
    'no_navbar_border': True,
    'sidebar': 'sidebar-light-primary',
    'brand_colour': 'navbar-white',
    'accent': 'accent-primary',
    'navbar_fixed': True,
    'sidebar_fixed': True,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': True,
    'footer_fixed': False,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-outline-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.BearerOrTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': int(os.getenv('API_PAGE_SIZE', '20')),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1'],
    'VERSION_PARAM': 'version',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_ANON_RATE', '100/hour'),
        'user': os.getenv('THROTTLE_USER_RATE', '1000/hour'),
        'auth_login': os.getenv('AUTH_LOGIN_THROTTLE_RATE', '5/minute'),
        'auth_register': os.getenv('AUTH_REGISTER_THROTTLE_RATE', '10/hour'),
        'password_reset': os.getenv('PASSWORD_RESET_THROTTLE_RATE', '5/hour'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API Oficial - Projeto Miranda',
    'DESCRIPTION': 'Documentação dos contratos de integração para o App e Painel Web',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.RequestContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=300,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'defaultdb'),
            'USER': os.getenv('DB_USER', 'avnadmin'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', ''),
            'PORT': int(os.getenv('DB_PORT', '3306')),
            'CONN_MAX_AGE': 300,
            'CONN_HEALTH_CHECKS': True,
        }
    }

if 'mysql' in DATABASES['default'].get('ENGINE', ''):
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].setdefault(
        'init_command',
        "SET sql_mode='STRICT_TRANS_TABLES'",
    )
    DATABASES['default']['OPTIONS'].setdefault('connect_timeout', 10)

    if DB_SSL_REQUIRED:
        ssl_options = {}
        ca_path = db_ca_cert_path()
        if ca_path:
            ssl_options['ca'] = ca_path
        DATABASES['default']['OPTIONS'].setdefault('ssl', ssl_options)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'pt-br')

TIME_ZONE = os.getenv('TIME_ZONE', 'America/Sao_Paulo')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET'),
    secure=True,
)
CLOUDINARY_MEDIA_FOLDER = os.getenv('CLOUDINARY_MEDIA_FOLDER', 'nexa').strip('/')

default_cors_origins = (
    'http://localhost:5173,http://127.0.0.1:5173,'
    'http://localhost:5177,http://127.0.0.1:5177'
    if DEBUG
    else ''
)
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS', default_cors_origins)

CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', False)
if CORS_ALLOW_ALL_ORIGINS and not DEBUG:
    raise ImproperlyConfigured('CORS_ALLOW_ALL_ORIGINS cannot be true when DEBUG is false.')

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173' if DEBUG else '')
if FRONTEND_URL:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL.rstrip('/'))

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')
if render_hostname:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_hostname}')
if FRONTEND_URL.startswith('https://'):
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL.rstrip('/'))

CORS_ALLOWED_ORIGINS = list(dict.fromkeys(CORS_ALLOWED_ORIGINS))
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
    if os.getenv('EMAIL_HOST')
    else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'noreply@projeto-miranda.local',
)

FIREBASE_ENABLED = env_bool('FIREBASE_ENABLED', False)
FIREBASE_PROJECT_ID = os.getenv('FIREBASE_PROJECT_ID', '')
FIREBASE_CLIENT_EMAIL = os.getenv('FIREBASE_CLIENT_EMAIL', '')
FIREBASE_PRIVATE_KEY = os.getenv('FIREBASE_PRIVATE_KEY', '')
PUSH_DISPATCH_ON_PUBLISH = env_bool('PUSH_DISPATCH_ON_PUBLISH', True)
PUSH_DISPATCH_ASYNC = env_bool(
    'PUSH_DISPATCH_ASYNC',
    bool(os.getenv('CELERY_BROKER_URL') or os.getenv('REDIS_URL')),
)

VIDEO_COMPRESSION_ENABLED = env_bool('VIDEO_COMPRESSION_ENABLED', True)
VIDEO_COMPRESSION_MAX_DIMENSION = int(
    os.getenv('VIDEO_COMPRESSION_MAX_DIMENSION', '1280')
)
VIDEO_COMPRESSION_CRF = int(os.getenv('VIDEO_COMPRESSION_CRF', '28'))
VIDEO_COMPRESSION_PRESET = os.getenv('VIDEO_COMPRESSION_PRESET', 'medium')
VIDEO_COMPRESSION_AUDIO_BITRATE = os.getenv(
    'VIDEO_COMPRESSION_AUDIO_BITRATE',
    '96k',
)
VIDEO_COMPRESSION_TIMEOUT_SECONDS = int(
    os.getenv('VIDEO_COMPRESSION_TIMEOUT_SECONDS', '180')
)
MAX_COMPRESSED_VIDEO_SIZE = int(
    os.getenv('MAX_COMPRESSED_VIDEO_SIZE_MB', '60')
) * 1024 * 1024
FFMPEG_BINARY = os.getenv('FFMPEG_BINARY', '')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REDIS_URL = os.getenv('REDIS_URL', '')
CACHE_TIMEOUT = int(os.getenv('CACHE_TIMEOUT', '300'))
DASHBOARD_REPORT_CACHE_TIMEOUT = int(os.getenv('DASHBOARD_REPORT_CACHE_TIMEOUT', '30'))

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
            },
            'TIMEOUT': CACHE_TIMEOUT,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'miranda-default-cache',
            'TIMEOUT': CACHE_TIMEOUT,
        }
    }

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', REDIS_URL or 'memory://')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', REDIS_URL or 'cache+memory://')
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = env_bool(
    'CELERY_TASK_ALWAYS_EAGER',
    not bool(os.getenv('CELERY_BROKER_URL') or REDIS_URL),
)
CELERY_TASK_EAGER_PROPAGATES = env_bool('CELERY_TASK_EAGER_PROPAGATES', DEBUG)
CELERY_TASK_IGNORE_RESULT = env_bool('CELERY_TASK_IGNORE_RESULT', True)

if not DEBUG and PUSH_DISPATCH_ASYNC and CELERY_BROKER_URL == 'memory://':
    raise ImproperlyConfigured(
        'PUSH_DISPATCH_ASYNC requires REDIS_URL or CELERY_BROKER_URL in production.'
    )

CELERY_BEAT_SCHEDULE = {
    'retry-failed-deliveries-hourly': {
        'task': 'api.tasks.retry_failed_deliveries',
        'schedule': 60 * 60,
    },
    'cleanup-old-delivery-logs-daily': {
        'task': 'api.tasks.cleanup_old_delivery_logs',
        'schedule': 60 * 60 * 24,
    },
    'mark-stale-deliveries-failed': {
        'task': 'api.tasks.mark_stale_deliveries_as_failed',
        'schedule': 60 * 30,
    },
    'deactivate-invalid-push-devices': {
        'task': 'api.tasks.deactivate_invalid_push_devices',
        'schedule': 60 * 60 * 6,
    },
    'backup-operational-evidence-daily': {
        'task': 'api.tasks.record_backup_operational_evidence',
        'schedule': 60 * 60 * 24,
    },
}

IS_VERCEL = env_bool('VERCEL', False)
ENABLE_FILE_LOGGING = env_bool('ENABLE_FILE_LOGGING', not DEBUG) and not IS_VERCEL

LOG_DIR = BASE_DIR / 'logs'
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')
DJANGO_LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', LOG_LEVEL)
API_LOG_LEVEL = os.getenv('API_LOG_LEVEL', LOG_LEVEL)

logging_handlers = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'console',
        'filters': ['request_context'],
    },
}

active_handlers = ['console']

if ENABLE_FILE_LOGGING:
    LOG_DIR.mkdir(exist_ok=True)
    logging_handlers['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(LOG_DIR / 'django.log'),
        'maxBytes': 10 * 1024 * 1024,
        'backupCount': 5,
        'formatter': 'json',
        'filters': ['request_context'],
    }
    active_handlers.append('file')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_context': {
            '()': 'api.logging_context.RequestContextFilter',
        },
    },
    'formatters': {
        'console': {
            'format': '%(levelname)s %(name)s %(message)s',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': (
                '%(asctime)s %(levelname)s %(name)s %(message)s '
                '%(pathname)s %(lineno)d %(request_id)s %(user_id)s'
            ),
        },
    },
    'handlers': logging_handlers,
    'root': {
        'handlers': active_handlers,
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': active_handlers,
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'api': {
            'handlers': active_handlers,
            'level': API_LOG_LEVEL,
            'propagate': False,
        },
    },
}

STORAGES = {
    "default": {
        "BACKEND": "api.storage.CloudinaryMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "api.storage.MirandaStaticFilesStorage",
    },
}

